name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install dependencies
      run: |
        go get .

    - name: Build for Raspberry Pi
      run: |
        GOARCH=arm GOARM=7 GOOS=linux go build -v ./...

    - name: Test
      run: go test -v ./...
